/*
  Copyright (C) 2014
  Alejandro Mujica (amujica@cenditel.gob.ve)
  José Ruiz (jruiz@cenditel.gob.ve)
  Julie Vera (jvera@cenditel.gob.ve)
 
  CENDITEL Fundación Centro Nacional de Desarrollo e Investigación en
  Tecnologías Libres
 
  Este programa es software libre; Usted puede usarlo bajo los términos de la
  licencia de software GPL versión 2.0 de la Free Software Foundation.
 
  Este programa se distribuye con la esperanza de que sea útil, pero SIN
  NINGUNA GARANTÍA; tampoco las implícitas garantías de MERCANTILIDAD o
  ADECUACIÓN A UN PROPÓSITO PARTICULAR.
  Consulte la licencia GPL para más detalles. Usted debe recibir una copia
  de la GPL junto con este programa; si no, escriba a la Free Software
  Foundation Inc. 51 Franklin Street,5 Piso, Boston, MA 02110-1301, USA.
*/

/*
  Autor:             Alejandro J. Mujica
  Fecha de creación: 29/09/2014
  Este archivo la inclusión de cabeceras generales utilizadas en el sistema.
*/


# ifndef INCLUDES_H
# define INCLUDES_H

// Biblioteca estándar de C
# include <cstdlib>
# include <cmath>
# include <cstdarg>

// Biblioteca estándar de C++
# include <iostream>
# include <string>
# include <sstream>
# include <fstream>
# include <stdexcept>
# include <tuple>
# include <limits>

// Biblioteca libxml++
/*
# include <libxml++/libxml++.h>
# include <libxml++/parsers/textreader.h>
# include <libxml++/nodes/node.h>
# include <libxml++/document.h>
# include <libxml++/parsers/domparser.h>
# include <libxml++/keepblanks.h>
*/
// Biblioteca Aleph-w
# include <tpl_dynArray.H>
# include <tpl_dynDlist.H>
# include <tpl_dynListQueue.H>
# include <tpl_dynSetTree.H>
# include <tpl_dynMapTree.H>
# include <ahPair.H>

# endif // INCLUDES_H

